module.exports = {
  GET_ORDER: "get-order",
  GET_ORDER_SUCCESS: 'get-order-success',
  GET_ORDER_ERROR: 'get-order-error',
  REMOVE_ORDER: "remove_order",
  REMOVE_ORDER_SUCCESS: 'remove-order-success',
  ADD_ORDER: "add-order",
  ADD_ORDER_SUCCESS:"add-order-success",
  ADD_ORDER_ERROR: "add-order-error",
  UPDATE_ORDER: "update-order",
  UPDATE_ORDER_SUCCESS: "update-order-success",
  UPDATE_ORDER_ERRROR: "update-order-error",
  QUERY_ORDERS: "query-orders",
  QUERY_ORDERS_SUCCESS: "query-orders_sucess",
  QUERY_ORDERS_ERROR: "query-orders_error",
  EXPORT_DB: "export-dabase",
  DB_CONNECTION_ERROR: 'db_connection_error',
  IMPORT_ORDERS: "import-orders",
  IMPORT_ORDERS_SUCCESS: "import-orders_success",
  IMPORT_ORDERS_ERROR: "import-orders_error",
  GET_PRODUCT: "get-product",
  GET_PRODUCT_SUCCESS: "get-product-success",
  GET_PRODUCT_ERROR: "get-product-error",
  GET_ALL_PRODUCTS: "get-all-products",
  GET_ALL_PRODUCTS_SUCCESS: "get-all-products",
  GET_ALL_PRODUCTS_ERROR: "get-all-products",
  GET_PRODUCTS_BY_CAT: "get-product-by-cat",
  GET_PRODUCTS_BY_CAT_SUCCESS: "get-product-by-cat-success",
  GET_PRODUCTS_BY_CAT_ERROR: "get-product-by-cat-error",
  GET_MENU:"get-menu",
  GET_MENU_SUCCESS: "get-menu-success",
  GET_MENU_ERROR: "get-menu-error",
  GET_CATEGORIES: "get-categories",
  GET_CATEGORIES_SUCCESS: "get-cateogories_success",
  GET_CATEGORIES_ERROR: "get-cateogories_error",
  ADD_FLAVOR: "add-flavor",
  ADD_FLAVOR_SUCCESS: "add-flavor_success",
  ADD_FLAVOR_ERROR: "add-flavor_error",
  REMOVE_FLAVOR: "remove-flavor",
  REMOVE_FLAVOR_SUCCESS: "remove-flavor_success",
  REMOVE_FLAVOR_ERROR: "remove-flavor_error",
  ADD_TOPPING: "add-topping",
  ADD_TOPPING_SUCCESS: "add-topping_success",
  ADD_TOPPING_ERROR: "add-topping_error",
  REMOVE_TOPPING: "remove-topping",
  REMOVE_TOPPING_SUCCESS: "remove-topping_success",
  REMOVE_TOPPING_ERROR: "remove-topping_error",
  GET_UNPAID: 'get-unpaid',
  GET_UNPAID_SUCCESS: "get-unpaid-success",
  //updater channels
  DOWNLOAD_UPDATE: "download_update",
  UPDATE_AVAILABLE: "update_available",
  UPDATE_NOT_AVAILABLE:"update_not_available",
  CHECK_FOR_UPDATE:"check_for_update",
  DOWNLOAD_COMPLETE:"download_complete",
  CONFIRM_UPDATE:"confirm_update",
  GET_VERSION: "get_version",
  GET_VERSION_RESPONSE: "get_version_response",
  GET_DATABASE_STATUS: "get_database_status",
  GET_DATABASE_STATUS_RESPONSE: 'get_database_status_response',
};
